site_name: The Things Network
theme: yeti

pages:
    - Overview: 'index.md'
    - Router: 'router.md'
    - Broker: 'broker.md'
    - Network Server: 'networkserver.md'
    - Handler: 'handler.md'
    - Development: 'development.md'
